# Serial port configuration
port: /dev/ttyUSB0        # Adjust if your Arduino appears elsewhere
baud: 57600

# General robot settings
use_base_controller: True
base_controller_rate: 30  # Hz

# Wheel & encoder specs
wheel_diameter: 0.065     # meters (e.g., 65 mm)
wheel_track: 0.20             # Distance between wheels
encoder_resolution: 3200  # ticks per revolution
max_speed: 1.0    

# PID control values
Kp: 20
Ki: 0
Kd: 12
Ko: 50

# Motor configuration
left_motor_reversed: False
right_motor_reversed: False

# Debug
publish_odom_tf: True     # Set to False if you're using static transforms elsewhere



use_base_controller: True
base_controller_rate: 10

